// -*- C++ -*-
//
// generated by wxGlade 1.0.3 on Sun Nov 28 01:37:36 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef WXGUI_HXX
#define WXGUI_HXX

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class G_MainDialog: public wxDialog {
public:
    // begin wxGlade: G_MainDialog::ids
    // end wxGlade

    G_MainDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:

protected:
    // begin wxGlade: G_MainDialog::attributes
    wxComboBox* command;
    wxTextCtrl* clipContent;
    wxButton* help;
    wxButton* button_OK;
    wxButton* button_CANCEL;
    // end wxGlade
}; // wxGlade: end class


#endif // WXGUI_H
