// -*- C++ -*-
//
// generated by wxGlade 1.0.3 on Sun Nov 28 01:37:36 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "wxgui.hxx"

// begin wxGlade: ::extracode
// end wxGlade



G_MainDialog::G_MainDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: G_MainDialog::G_MainDialog
    SetSize(wxSize(658, 385));
    SetTitle(wxT("wxClip"));
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(sizer_3, 1, wxEXPAND, 0);
    const wxString command_choices[] = {};
    command = new wxComboBox(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, command_choices, wxCB_DROPDOWN);
    sizer_3->Add(command, 0, wxEXPAND, 0);
    clipContent = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxHSCROLL|wxTE_MULTILINE|wxTE_READONLY);
    sizer_3->Add(clipContent, 1, wxEXPAND, 0);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(sizer_2, 0, wxALL|wxEXPAND, 4);
    help = new wxButton(this, wxID_HELP, wxEmptyString);
    sizer_2->Add(help, 0, wxALL|wxSHAPED, 0);
    sizer_2->Add(20, 20, 1, 0, 0);
    button_OK = new wxButton(this, wxID_OK, wxEmptyString);
    button_OK->SetDefault();
    sizer_2->Add(button_OK, 0, 0, 0);
    button_CANCEL = new wxButton(this, wxID_CANCEL, wxEmptyString);
    sizer_2->Add(button_CANCEL, 0, 0, 0);
    
    SetSizer(sizer_1);
    SetAffirmativeId(button_OK->GetId());
    SetEscapeId(button_CANCEL->GetId());
    
    Layout();
    // end wxGlade
}

